/// <reference types="cypress" />
import HomePage from "../pages/home"
import LinkPage from "../pages/links"
import NodePage from "../pages/node"

Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})

context('Create Differnt Content type', () => {
  beforeEach(() => {
    cy.fixture('example').as('testdata')
    cy.loginSession(Cypress.env.cyAdminUser,Cypress.env.cyAdminPassword)
  })

  it('Create "Ad" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Ad')
    cy.get('h1').should('contain', 'Create Ad')
    cy.get('#edit-title-0-value').type("This is test Ad node")
    cy.get('#edit-submit').click()
    cy.contains('has been created').should('be.visible')
    cy.deleteNode()
    cy.contains('Log out').click({force:true})
  }) 

  it('Create "Ad Campaign" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Ad Campaign')
    cy.get('h1').should('contain', 'Create Ad Campaign')
    cy.get('#edit-title-0-value').type("This is test Ad Campaign node")
    //cy.get('#edit-field-ad-active-dates-0-value-date').type('MM/DD/YYYY')
    //cy.get('#edit-field-ad-active-dates-0-end-value-date').type(dayjs().format('MM/DD/YYYY'))
    cy.get('#edit-submit').click()
    cy.contains('has been created').should('be.visible')
    cy.deleteNode()
    cy.contains('Log out').click({force:true})
  }) 

  it('Create "Article" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Article - Education Article')
    cy.get('h1').should('contain', 'Create Article - Education Article')
    cy.get('#edit-title-0-value').type("This is test Article node")
    cy.get('#edit-field-disclosure').select('Careers')
    cy.get('.form-checkbox').first().check().should('be.checked')
    cy.get("#edit-group-education-article").click()
    cy.get('#edit-body-0-value').type("This is a test. Please ignore!")
    cy.get('#edit-submit').click()
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

  it('Create "Associate" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Associate')
    cy.get('h1').should('contain', 'Create Associate')
    cy.get('#edit-title-0-value').type("This is test Associate node")
    //cy.get('#edit-group-info > .claro-details__summary').click()
    NodePage.associate_info().click()
    NodePage.associate_nmls().type(this.testdata.NMLS,{force:true})
    NodePage.associate_info_jobTitle().type('Financial Analyst')
    NodePage.associate_desgination().type(this.testdata.Designation,{delay:250})
    cy.get('.js-form-item-body-0-value').within(() =>{
      cy.get('#edit-body-0-value').type(this.testdata.body)
    })
    cy.contains('Contact').click()
    NodePage.associate_contact_officeNumber().type(this.testdata.phone)
    NodePage.associate_contact_email().type(this.testdata.email)
    cy.get('#edit-group-locations > .claro-details__summary').click()
    cy.get('#edit-field-associate-locations-0-target-id').type(this.testdata.Locations)
    cy.contains('Tags').click()
    NodePage.associate_tags_associateType().select('Lenders')
    cy.get('[aria-controls="edit-group-links"]').click()
    cy.get('#edit-field-website-0-uri').type("/pfelton")
    cy.get('#edit-field-website-0-title').type('Vist my Site')
    /*
    //Click on Media tab
    cy.get('#edit-group-media > .claro-details__summary').click()
    cy.get('#edit-field-landscape-profile-image-open-button').click()
    cy.get('.js-media-library-view').contains('Table').click()
    cy.get('tbody > :nth-child(1) > .views-field-media-library-select-form').click()
    cy.get('.ui-dialog-buttonset > .media-library-select').click()
    cy.wait(1000)
    cy.get('#edit-field-portrait-profile-image-open-button').click()
    cy.get('.views-display-link-widget_table').click()
    cy.get('tbody > :nth-child(1) > .views-field-media-library-select-form').click()
    cy.get('.ui-dialog-buttonset > .media-library-select').click()
    cy.wait(1000)
    */

    /*
    cy.get('[type="checkbox"]').first().check().should('be.checked')
    cy.get('#edit-field-designation-0-target-id').type('AIF (951)',{delay:250})
    cy.get('#edit-field-job-title-0-value').type('QA Analyst')
    cy.get('#edit-field-office-number-0-value').type(this.testdata.phone)
    cy.get('#edit-field-email-0-value').type(this.testdata.email)
    cy.get('#edit-field-associate-type').select('Advisors')
    cy.get('#edit-field-landscape-profile-image-open-button').click()
    cy.get('.js-media-library-view').contains('Table').click()
    cy.get('tbody > :nth-child(1) > .views-field-media-library-select-form').click()
    cy.get('.ui-dialog-buttonset > .media-library-select').click()
    cy.wait(1000)
    cy.get('#edit-field-portrait-profile-image-open-button').click()
    cy.get('.views-display-link-widget_table').click()
    cy.get('tbody > :nth-child(1) > .views-field-media-library-select-form').click()
    cy.get('.ui-dialog-buttonset > .media-library-select').click()
    cy.wait(1000)
    */
    cy.contains('Legacy fields').click()
    NodePage.associate_legacy_image().attachFile('atesavis.jpeg')
    cy.wait(2000)

    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

   it('Create "Basic Page" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Basic Page')
    cy.get('h1').should('contain', 'Create Basic Page')
    cy.get('#edit-title-0-value').type("This is test Basic node")
    cy.get('[type="radio"]').first().should('be.checked')
    cy.get('#edit-field-disclosure').select('Careers')
    cy.get('#edit-body-0-value').type("This is a test. Please ignore!")
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

  it('Create "Calculators" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Calculators')
    cy.get('h1').should('contain', 'Create Calculators')
    cy.get('#edit-title-0-value').type("This is test Calculators node")
    cy.get('[type="checkbox"]').first().check().should('be.checked')
    cy.get('#edit-group-iframe-calculator').click()
    cy.get("#edit-field-calculator").selectNth(1)
    cy.get('#edit-body-0-summary').type("This is a test Calculator")
    cy.get('#edit-body-0-value').type("This is a test. Please ignore!")
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

   it('Create "Campaign Landing Pages" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Campaign Landing Pages')
    cy.get('h1').should('contain', 'Create Campaign Landing Pages')
    cy.get('#edit-title-0-value').type('his is test Campaign Landing Pages node')
    cy.get('#edit-field-disclosure').select(2)
    cy.get('#edit-field-field-callout-phone-number').select(2)
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

   it('Create "External Ad" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('External Ad')
    cy.get('h1').should('contain', 'Create External Ad')
    cy.get('#edit-title-0-value').type("This is test External Ad node")
    cy.get('#edit-field-ad-url-0-uri').type('Shane Stover (7161)')
    cy.get('#edit-field-ad-image-open-button').click()
    cy.get('.js-media-library-view').contains('Table').click()
    cy.get('tbody > :nth-child(1) > .views-field-media-library-select-form').click()
    cy.get('.ui-dialog-buttonset > .media-library-select').click()
    cy.wait(1000)
    cy.get('#edit-submit').click({force:true})
    //cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

  it('Create "Financing" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Financing')
    cy.get('h1').should('contain', 'Create Financing')
    cy.get('#edit-title-0-value').type('his is test Financing node')
    cy.get('#edit-field-financing-description-0-value').type('This is test description')
    cy.get('#edit-field-financing-link-0-uri').type('Shane Stover (7161)')
    cy.get('#edit-field-financing-link-0-title').type("Test link")
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

    it('Create "Phone Number" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Phone Number')
    cy.get('h1').should('contain', 'Create Phone Number')
    cy.get('#edit-title-0-value').type(this.testdata.phone)
    cy.get('[type="checkbox"]').should('be.checked')
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

    it('Create "Private Bank Location" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Private Bank Location')
    cy.get('h1').should('contain', 'Create Private Bank Location')
    cy.get('#edit-title-0-value').type('his is test Private Bank Location node')
    cy.get('#edit-field-phone-number-0-value').type(this.testdata.phone)
    cy.get('#edit-field-private-bank-location-link-0-uri').type('Shane Stover (7161)')
    cy.get('#edit-field-private-bank-location-link-0-title').type("Test link")
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })

    it('Create "Webform" Content Type', function(){
    cy.visit('/node/add')
    cy.get('h1').should('contain', 'Add content')
    cy.addNode('Webform')
    cy.get('h1').should('contain', 'Create Webform')
    cy.get('#edit-title-0-value').type('his is test Webform node')
    cy.get('#edit-field-disclosure').select(2)
    cy.get('#edit-body-0-value').type("This is test")
    cy.get("#edit-webform-0-target-id").select(1)
    cy.get('#edit-submit').click({force:true})
    cy.contains('has been created').should('be.visible')
    //cy.deleteNode()
    cy.contains('Log out').click({force:true})
  })




  })